### ISSUE TITLE
Update README With All Info

### ISSUE THREAD

**Issue by sschneller** [CSC480/laker-polling#2]
All groups should have full roster listed on the README, and maybe short snippet describing the point of the team if you want.

**Comment by sschneller** [comment]
Database, GUI, and Engine need to update their goals

**Comment by apjansing** [comment]
People may be able to link to their GitHub or CS accounts in the README as well.
`[@sschneller](https://github.com/sschneller)`
[@sschneller](https://github.com/sschneller)

This might make it easier for later professor grading **or** just get people more comfortable with the idea of using markdown. I know how I felt in CSC380 and having no clue where to start with editing the README. 😄

**Comment by Ryan-Staring** [comment]
Engine needs to update their goals
